### ISSUE TITLE
ArrowFunction is not supported by ECMA 5.1.

### ISSUE THREAD

**Issue by RuneStone0** [PiotrDabkowski/pyjsparser#33]
Unable to parse: https://onfido.com/js/supported-docs.js
```
Traceback (most recent call last):
  File "scrape_onfido.py", line 12, in <module>
    print(parse(data))
  File "/venv/lib/python3.7/site-packages/pyjsparser/parser.py", line 3018, in parse
    return p.parse(javascript_code)
  File "/venv/lib/python3.7/site-packages/pyjsparser/parser.py", line 3010, in parse
    raise self.createError(self.lineNumber, self.lastIndex, unicode(e))
pyjsparser.pyjsparserdata.JsSyntaxError: Line 1: ArrowFunction is not supported by ECMA 5.1.
```

**Comment by PiotrDabkowski** [comment]
ArrowFunction is not supported by ECMA 5.1.
